question_data = [
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Science: Computers",
            "question": "The very first recorded computer &quot;bug&quot; was a moth found inside a Harvard Mark II computer.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Science: Computers",
            "question": "The HTML5 standard was published in 2014.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Science: Computers",
            "question": "All program codes have to be compiled into an executable file in order to be run. This file can then be executed on any machine.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Science: Computers",
            "question": "AMD created the first consumer 64-bit processor.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Science: Computers",
            "question": "The last Windows operating system to be based on the Windows 9x kernel was Windows 98.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Science: Computers",
            "question": "The first dual-core CPU was the Intel Pentium D.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Science: Computers",
            "question": "The &#039;Raspberry Pi&#039; series of single-board computers were created in the United States.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Science: Computers",
            "question": "It&#039;s not possible to format a write-protected DVD-R Hard Disk.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Science: Computers",
            "question": "&quot;Windows NT&quot; is a monolithic kernel.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Science: Computers",
            "question": "MacOS is based on Linux.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
]
